-- BuySafe error report table
-- Run this once in the Supabase SQL Editor before using the report form.

CREATE TABLE IF NOT EXISTS svc_error_report (
  report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asin TEXT NOT NULL,
  product_title TEXT,
  source_url TEXT,
  report_type TEXT NOT NULL CHECK (
    report_type IN (
      'price_tax',
      'hs_code',
      'regulation',
      'product_info',
      'page_error',
      'other'
    )
  ),
  detail TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'REVIEWING', 'RESOLVED', 'REJECTED')),
  reporter_user_id UUID,
  user_agent TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_svc_error_report_created_at
  ON svc_error_report (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_svc_error_report_asin
  ON svc_error_report (asin);

CREATE INDEX IF NOT EXISTS idx_svc_error_report_status
  ON svc_error_report (status);

ALTER TABLE svc_error_report
  ALTER COLUMN status SET DEFAULT 'OPEN';

UPDATE svc_error_report
SET status = 'OPEN'
WHERE status IS NULL;

ALTER TABLE svc_error_report
  ALTER COLUMN status SET NOT NULL;
